DROP DATABASE IF EXISTS DBEXERCICIO010;

CREATE DATABASE DBEXERCICIO010;

USE DBEXERCICIO010;

CREATE TABLE ARTESA (
  IDARTESA INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45),
  SEXO CHAR(1),
  E_MAIL VARCHAR(45),
  SENHA VARCHAR(45),
  CELULAR VARCHAR(15),
  RUA VARCHAR(150),
  NUMERO INT,
  CEP VARCHAR(8),
  CIDADE VARCHAR(45),
  ESTADO CHAR(2),
  PRIMARY KEY (IDARTESA));
  
  CREATE TABLE PRODUTO (
  IDPRODUTO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45),
  DESCRICAO VARCHAR(150),
  TIPO ENUM('REDE','TAPETE'),
  VALOR NUMERIC(8,2),
  PRIMARY KEY (IDPRODUTO))