DROP DATABASE IF EXISTS EXEMPLO0002;

CREATE DATABASE EXEMPLO0002;

USE EXEMPLO0002;

CREATE TABLE ENTIDADE_A (
ID_A INT NOT NULL,
PRIMARY KEY (ID_A)
);

CREATE TABLE ENTIDADE_B (
ID_B INT NOT NULL,
ID_A INT,
PRIMARY KEY (ID_B),
FOREIGN KEY (ID_A) REFERENCES ENTIDADE_A (ID_A)
);