DROP DATABASE IF EXISTS DBEXERCICIO012;

CREATE DATABASE DBEXERCICIO012;

USE DBEXERCICIO012;

CREATE TABLE IF NOT EXISTS PESSOA (
  ID_PESSOA INT NOT NULL AUTO_INCREMENT,
  DATA_DE_NASCIMENTO DATE,
  NOME_PAI VARCHAR(100),
  NOME_MAE VARCHAR(100),
  ID_CPF CHAR(11),
  DATA_DE_SOLICITACAO DATE,
  DATA_DE_EMISSAO DATE,
  LOCAL_DE_EMISSAO VARCHAR(45),
  PRIMARY KEY (ID_PESSOA, ID_CPF))