DROP DATABASE IF EXISTS DBEXERCICIO006;

CREATE DATABASE DBEXERCICIO006;

USE DBEXERCICIO006;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100), 
	IDADE INT, 
	RUA VARCHAR(100), 
	NUMERO INT, 
	BAIRRO VARCHAR(100), 
	CIDADE VARCHAR(100), 
	ESTADO VARCHAR(100), 
	CEP VARCHAR(30), 
	COMPLEMENTO VARCHAR(100),


  PRIMARY KEY (IDALUNO)
  );