DROP DATABASE IF EXISTS DBEXERCICIO015;

CREATE DATABASE DBEXERCICIO015;

USE DBEXERCICIO015;

CREATE TABLE IF NOT EXISTS COMPUTADOR (
  ID_COMPUTADOR INT NOT NULL AUTO_INCREMENT,
  MODELO VARCHAR(45),
  MASCARA VARCHAR(200),
  ENDERECO VARCHAR(100),
  FABRICANTE VARCHAR(100),
  PRIMARY KEY (ID_COMPUTADOR)
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
  ID_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT,
  REPONSAVEL VARCHAR(45),
  RAMAL VARCHAR(15),
  NOME_DEPARTAMENTO VARCHAR(100),
  COMPUTADOR_ID_COMPUTADOR INT NOT NULL,
  PRIMARY KEY (ID_DEPARTAMENTO, COMPUTADOR_ID_COMPUTADOR),
  FOREIGN KEY (COMPUTADOR_ID_COMPUTADOR) REFERENCES COMPUTADOR (ID_COMPUTADOR)
)