DROP DATABASE IF EXISTS DBEXERCICIO008;

CREATE DATABASE DBEXERCICIO008;

USE DBEXERCICIO008;

CREATE TABLE ELEITOR (
  IDELEITOR INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100),
  SEXO CHAR(1),
  EMAIL VARCHAR(100),
  DATA_DE_NASCIMENTO DATE,
  CIDADE VARCHAR(100),
  BAIRRO VARCHAR(100),
  CEP INT,
  ENDERECO_COMPLETO VARCHAR(200),
  TELEFONE_CEl INT,
  TELEFONE_RES INT,
  TELEFONE_CONT INT,
  PRIMARY KEY (IDELEITOR))