DROP DATABASE IF EXISTS DBEXERCICIO009_1;

CREATE DATABASE DBEXERCICIO009_1;

USE DBEXERCICIO009_1;

CREATE TABLE ANIMAL (
  IDANIMAL INT NOT NULL AUTO_INCREMENT,
  TIPO ENUM('CÃO','GATO'),
  PORTE VARCHAR(15),
  SEXO CHAR(1),
  NOME VARCHAR(45),
  PRIMARY KEY (IDANIMAL))