DROP DATABASE IF EXISTS DBEXERCICIO009;

CREATE DATABASE DBEXERCICIO009;

USE DBEXERCICIO009;

CREATE TABLE CANDIDATO (
  IDCANDIDATO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45),
  SEXO CHAR(1),
  E_MAIL VARCHAR(45),
  SENHA VARCHAR(45),
  FONE_1 VARCHAR(15),
  FONE_2 VARCHAR(15),
  FONE_3 VARCHAR(15),
  PRIMARY KEY (IDCANDIDATO))