DROP DATABASE IF EXISTS DBEXERCICIO007;

CREATE DATABASE DBEXERCICIO007;

USE DBEXERCICIO007;

CREATE TABLE ALUNO (
  IDALUNO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45),
  DATA_DE_NASCIMENTO DATE,
  NUMERO_CEL INT,
  DDD_CEL INT,
  NUMERO_RES INT,
  DDD_RES INT,
  NUMERO_CONT INT,
  DDD_CONT INT,
  NOME_DO_CONTATO VARCHAR(45),
  
  PRIMARY KEY (IDALUNO))
