DROP DATABASE IF EXISTS DBEXERCICIO005;

CREATE DATABASE DBEXERCICIO005;

USE DBEXERCICIO005;

CREATE TABLE VEICULO (

  IDVEICULO INT NOT NULL AUTO_INCREMENT,
  NUMERO_DO_CHASSI INT,
  MARCA VARCHAR(45),
  ANO_DO_MODELO INT,
  ANO_DE_FABRICACAO INT,
  COR VARCHAR(45),
  PLACA VARCHAR(8),
  PRIMARY KEY (IDVEICULO)
  );