DROP DATABASE IF EXISTS DBEXERCICIO004;

CREATE DATABASE DBEXERCICIO004;

USE DBEXERCICIO004;

CREATE TABLE USUARIO (
  CODIGO INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(45),
  EMAIL VARCHAR(100),
  INVOCADOR VARCHAR(24),
  TEAM VARCHAR(45),
  SENHA VARCHAR(45),
  PRIMARY KEY (CODIGO)
  );
  
  CREATE TABLE TEAM (
  IDTIME INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45),
  TAG VARCHAR(4),
  LOGO VARCHAR(200),
  PRIMARY KEY (IDTIME))