DROP DATABASE IF EXISTS DBEXERCICIO016;

CREATE DATABASE DBEXERCICIO016;

USE DBEXERCICIO016;

CREATE TABLE IF NOT EXISTS DEPENDENTE (
  ID_DEPENDENTE INT NOT NULL AUTO_INCREMENT,
  DATA_DE_NASCIMENTO DATE,
  NOME VARCHAR(45),
  PRIMARY KEY (ID_DEPENDENTE)
);

CREATE TABLE IF NOT EXISTS TITULAR (
  ID_TITULAR INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45),
  CPF VARCHAR(200),
  PLANO_DE_SAUDE VARCHAR(100),
  DATA_DE_NASCIMENTO DATE,
  DEPENDENTE_ID_DEPENDENTE INT,
  PRIMARY KEY (ID_TITULAR),
  FOREIGN KEY (DEPENDENTE_ID_DEPENDENTE) REFERENCES DEPENDENTE (ID_DEPENDENTE)
);